server:
  port: 40000
spring:
  application:
    name: mall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: 192.168.182.150
  session:
    store-type: redis
#开启feign对sentinel的支持
#配置线程池
mall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true