spring:
  application:
    name: mall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        tpl_id: TP1711063
        appcode: 7b8165578cfe4e7986257d6fac266355
#      access-key: LTAI5tHgiKL82NxTrmD7EbLq
#      secret-key: oN4MFWVlzO9qm5Vt0TIWG43w1ZFmbl
#      oss:
#        bucket: hucheng-mall
#        endpoint: oss-cn-shenzhen.aliyuncs.com
      access-key: LTAI4FwvfjSycd1APnuG9bjj
      secret-key: O6xaxyiWfSIitcOkSuK27ju4hXT5Hl
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-hello
server:
  port: 30000

